Repository tetrabiodistributed/project-tetra-display, pull requests merged in 2020-08, with the labels that each got.

#24 Add ci for python unittests no docker
  .github/workflows/unittests.yml
  README.md
  runtests.sh
  setup.sh
Labels: devops

#7 Closes #5: add github workflow for running unittests
  .github/workflows/unittests.yml
  README.md
  runtests.sh
  setup.sh
Labels: devops

#10 Fix/behave run backend
  env.sh
  features/steps/runs_backend_from_docker_image.py
  runtests.sh
  setup.sh
Labels: bug

#28 Feature/display test 12
  README.md
  basic_websocket.py
  features/descriptors_are_drawn_to_the_display.feature
  features/environment.py
  features/fixtures.py
  features/gets_sensor_data.feature
  features/runs_backend_from_docker_image.feature
  features/steps/descriptors_are_drawn_to_the_display.py
  features/steps/runs_backend_from_docker_image.py
  requirements.txt
  server.py
  services.conf
  setup.sh
  static/index.html
  static/style.css
  zmq_test_server.py
Labels: feature

#32 Feature/display Closes #13 Closes #31
  .github/workflows/unittests.yml
  .gitignore
  README.md
  Tests/test_server.py
  basic_websocket.py
  chromedriverinstall.sh
  features/calculating_tubing_descriptors.feature
  features/descriptors_are_drawn_to_the_display.feature
  features/environment.py
  features/fixtures.py
  features/gets_sensor_data.feature
  features/runs_backend_from_docker_image.feature
  features/steps/calculating_tubing_descriptors.py
  features/steps/descriptors_are_drawn_to_the_display.py
  features/steps/runs_backend_from_docker_image.py
  patienttubingdescriptorcalculator.py
  requirements.txt
  runtests.sh
  server.py
  services.conf
  setup.sh
  static/index.html
  static/main.js
  static/style.css
Labels: feature

#29 renamed variables to line up with the data sheet. Closes #26
  spl06_007.py
Labels: bug
